Repository kensonjohnson/three-bet, pull requests merged in 2023-11, with the labels that each got.

#1 Remove file
  .github/workflows/ci.yaml
Labels: bug

#3 Kenson/add linter
  .eslintrc.cjs
  package-lock.json
  package.json
Labels: enhancement

#7 Kenson/models
  src/controllers/root-controller.ts
  src/models/Card.ts
  src/models/Deck.ts
  src/server.ts
Labels: enhancement

#9 Update readme with lint command
  README.md
Labels: documentation

#11 Add burnOne and dealManyCards methods
  src/models/Deck.ts
Labels: enhancement

#14 Player Model
  package-lock.json
  package.json
  src/models/Deck.ts
  src/models/Player.ts
  tsconfig.json
Labels: enhancement

#15 Adds Jest and Initial unit tests
  .gitignore
  frontend/tsconfig.json
  jest.config.cjs
  package-lock.json
  package.json
  src/controllers/root-controller.test.ts
  src/controllers/root-controller.ts
  src/models/Card.test.ts
  src/models/Deck.test.ts
  src/models/Deck.ts
  src/models/Player.test.ts
  src/server.ts
  tsconfig.json
Labels: documentation, enhancement
