Repository kensonjohnson/three-bet, pull requests merged in 2023-12, with the labels that each got.

#18 Continuous Integration Pipeline
  .eslintrc.cjs
  .github/workflows/ci.yaml
  src/models/Deck.ts
Labels: enhancement

#19 Refactor Deck Model
  src/models/Deck.test.ts
  src/models/Deck.ts
Labels: enhancement

#21 Pull Request Template
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: enhancement

#22 Removed properties that should be on the view
  src/models/Card.test.ts
  src/models/Card.ts
Labels: bug

#23 Fix Visibility of Pull Request Template
  .github/pull_request_template.md
Labels: bug, documentation

#24 Add Table model and Evaluate logic
  src/models/Deck.ts
  src/models/Evaluate.ts
  src/models/Player.ts
  src/models/Table.ts
Labels: enhancement

#25 Rework Evaluate.ts Model
  src/models/Card.ts
  src/models/Evaluate.test.ts
  src/models/Evaluate.ts
Labels: enhancement

#26 Kenson/optimize evaluate model
  src/models/Evaluate.ts
  tsconfig.json
Labels: enhancement

#28 Changed wording to better fit concerns
  .github/pull_request_template.md
Labels: documentation
